### ISSUE TITLE
Can I get pkl file?

### ISSUE THREAD

**Issue by seunghee-han** [MartinPernus/FICE#7]
Hello, have read your paper, and I think your paper is very good.
so I've implemented the code, and I want to even train the model myself.
I need viton.pkl trained on viton dataset with stylegan2.
I have the viton dataset, but I can't get a pretrained model by training stylegan.

![Screenshot from 2023-05-04 16-06-38](https://user-images.githubusercontent.com/54052702/236134954-36589aee-e640-4f89-bc3b-a9d98601dbba.png)
![Screenshot from 2023-05-04 16-11-57](https://user-images.githubusercontent.com/54052702/236135018-aaeddfae-59e8-41e3-830d-489fb6e2ac73.png)

Can i get 'viton.pkl' ?
Please contact hee11273@gmail.com

Thank You.

**Comment by MartinPernus** [comment]
Hey,

the converted file ('.pt' extension) is actually 'generator.pt', already available when you download the checkpoints. This is the state dict of a VITON-trained StyleGAN2.

I suggest using the state dict in form of .pt files instead of pkl files since the latter cause significant issues when loading the data.
